config/routes.rb
Rails.application.routes.draw do
  # get 'box_echanges/new'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  root "vinyards#index"
  # Defines the root path route ("/")
  # root "posts#index"

  #

  resources :appellations

  resources :cuvee_colors

  resources :vinyards do
    member do
      get "shipments_csv", to: "vinyards#shipments_to_csv"
      get "pick_ups_csv", to: "vinyards#pick_ups_to_csv"
      get "edit_description", to: "vinyards#edit_description"
      get "edit_region", to: "vinyards#edit_region"
      get "edit_address", to: "vinyards#edit_address"
    end
    resources :dividendes
    resources :dividende_cuvee_colors
    resources :slots
    resources :vinyard_appellations do
      resources :cuvees
      resources :cuvee_colors
    end
  end

  resources :users, only: [:show] do
    resources :exchanges, only: [:index, :create]
    member do
      post "accept", to: "exchanges#accepted_exchanges"
      post "reject", to: "exchanges#rejected_exchanges"
    end
    resources :box_exchanges, only: [:new, :destroy]
    resources :deliveries, only: [:update]
    resources :addresses, only: [:new, :create, :edit, :update, :destroy]
    resources :boxes, only: [:edit, :update] do
      resources :pick_up_dates, only: [:new, :create, :edit, :update]
    end
  end

    get 'exchanges/load_boxes', to: 'exchanges#load_boxes'

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: [:user, :admin]

  has_many :boxes, dependent: :destroy
  has_many :dividendes, through: :boxes
  has_many :exchanges_as_initator, foreign_key: "initiator_id", class_name: "Exchange", dependent: :destroy
  has_many :exchanges_as_recipient, foreign_key: "recipient_id", class_name: "Exchange", dependent: :destroy
  has_many :stock_owners, dependent: :destroy
  has_many :vinyards, through: :stock_owners
  has_one :delivery, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :vinyards, foreign_key: "admin_id", dependent: :nullify
  after_create :create_delivery

  validates :pseudo, presence: true, uniqueness: true

  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  accepts_nested_attributes_for :addresses, allow_destroy: true
  accepts_nested_attributes_for :boxes, allow_destroy: true










  def self.ransackable_associations(auth_object = nil)
    ["boxes", "dividendes", "exchanges_as_initator", "exchanges_as_recipient", "stock_owners", "vinyards", "delivery","vinyard", "addresses"]
  end

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "delivery_address", "id", "id_value", "pseudo", "vinyard_id","updated_at",
     "email", "role", "encrypted_password", "reset_password_token", "reset_password_sent_at",]
  end

  private

  def create_delivery
    Delivery.create(user: self, delivery_method:"pickup")
  end


end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  def new
    super
  end


  def create
    @user = User.new(sign_up_params)
    if @user.save
      sign_in(@user)
      redirect_to root_path
    else
      @user.errors.full_messages.each do |message|
        flash[:error] = message
      end
      render :new

    end
  end

  private

  def sign_up_params
    params.require(:user).permit(:email, :password, :password_confirmation, :pseudo)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    current_year = Time.current.year
    @current_boxes = Box.joins(:dividende).left_joins(:pick_up_date).where(user_id: @user.id).where("dividendes.year = ?", current_year)
    .order(Arel.sql("CASE
    WHEN boxes.delivery_method = 'shipment' THEN dividendes.shipping_date
    ELSE pick_up_dates.date
    END ASC"))

    @non_exchangeable_boxes = @user.boxes.where(exchangeable: false)
                 .joins(:dividende)
                 .where(dividende: { year: current_year })
                 .includes(:vinyard)
                 .group_by(&:vinyard)

    @exchangeable_boxes = @user.boxes.where(exchangeable: true)
                 .joins(:dividende)
                 .where(dividende: { year: current_year })
                 .includes(:vinyard)
                 .group_by(&:vinyard)
    @exchange = Exchange.new
    @exchange.box_exchanges.build
    @delivery = @user.delivery
    if @user.addresses.any?
      @addresses = @user.addresses
    end
    if @delivery.address
        @delivery_address = @delivery.address
    end

  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_addresses.html.erb
<%=fields_for :addresses, Address.new do |address| %>
  <%=address.text_field :title, placeholder: "title of the address" %>
  <%=address.text_field :name, placeholder: "name"%>
  <%=address.text_field :street, placeholder: "street and n°"%>
  <%=address.text_field :city, placeholder: "city"%>
  <%=address.text_field :zip, placeholder: "zip code"%>
  <%=address.text_field :country, placeholder: "country"%>
  <div>
    <%=address.submit "Save"%>
  </div>
<%end%>

app/views/users/_delivery_form.html.erb
<div class="bggrey">
  <div class="flex-column padding" data-controller="preferences">
    <div class=" flex-column gap2 border-bottom margin-bottom1 margin-top1">
      <div class="list flex-column gap1 ">
        <% if @user.addresses.length > 0%>
        <h3 class="margin-bottom1">registered addresses :</h3>
          <%@user.addresses.each do |address|%>
            <div class="address flex space-between" id="<%= dom_id(address)%>">
              <div class="border address-title flex">
                <p class = "margin0"><%=address.title%></p>
              </div>
              <div class="buttons flex space-between">
                <%= link_to "Edit", edit_user_address_path(@user, address), data: { turbo_stream: true }, class: 'button'%>
                <%= button_to "X", user_address_path(@user, address), method: :delete, data: { turbo_confirm: "Are you sure?", turbo_stream: true }, class: 'delete' %>
              </div>
            </div>
          <%end%>
        <% else%>
          <p>No address registered yet</p>
        <%end%>
      </div>
      <div class="margin-bottom1">
        <%= form_with model: Address.new, url:user_addresses_path(@user) do |f| %>

          <div id="create_address" class="flex-column gap1">
            <div>
            <%=button_tag "Add Address", formaction:new_user_address_path(@user), formmethod: :get, data:{ turbo_stream: true } %>
            </div>
          </div>

        <%end%>

      </div>
    </div>
    <div class="delivery ">
      <h3 class="margin-bottom1">Default settings</h3>
      <p class="italic margin-top1 margin-bottom1"> will be applied to each new box, but can be customize by clicking "edit preferences"</p>
      <%= form_with model: @delivery, url:user_delivery_path(@user, @delivery) do |f| %>
        <div class= "flex-column gap2 ">
          <div class>
            <div class="flex gap1">
              <p>default delivery method :</p>
            <%=f.select :delivery_method, ["pickup", "shipment"], {}, data: {action: "change->preferences#ToggleAddress", target: "preferences.deliveryMethod"} %>
            </div>
          </div>
          <div id="address-select" data-preferences-target="address" class= "flex gap1">
          <p>Choose default address :</p>
            <%= f.select :address_id, @user.addresses.map {|address| [address.title, address.id]}, {prompt: "select default address"}  %>
          </div>
          <div>

          <%= f.submit "save"%>
          </div>
        </div>
      <%end%>
    </div>
    <div class="border-top flex-column gap1 margin-top1">
      <h3 class="margin-top1">My shares :</h3>
      <%@user.stock_owners.each do |s|%>
        <%= "#{s.vinyard.name} (#{s.quantity})"%>
        <%end%>

    </div>
  </div>

</div>

app/views/users/_edit_address.html.erb
<%= form_with model: address, url: user_address_path(address.user, address), method: :patch, data: { turbo_frame: dom_id(address) } do |f| %>
  <%= f.text_field :title, placeholder: "Title of the address" %>
  <%= f.text_field :name, placeholder: "Name" %>
  <%= f.text_field :street, placeholder: "Street and n°" %>
  <%= f.text_field :city, placeholder: "City"%>
  <%= f.text_field :zip, placeholder: "ZIP code" %>
  <%= f.text_field :country, placeholder: "Country" %>
  <%= f.submit "Save" %>
<% end %>

app/views/users/_edit_box.html.erb
<div data-controller="preferences" class="disable-outside-clik">
  <div class="modale justify-center" >
    <%= form_with model: @box, url: user_box_path(@user, @box), method: :patch do |f| %>
      <div class="flex-column height100 space-between">
        <div>
          <h3 class="margin-bottom1"><%="#{@box.dividende.vinyard.name} #{@box.dividende.year}"%></h3>
          <div data-preferences-target="shippingDate">
            <p>delivery date from: <%="#{@box.dividende.shipping_date.strftime("%d %B %Y")}"%></p>
          </div>
          <div id=vinyard-address data-preferences-target="vinyardAddress" class="hidden">
            <p>pickup address: <%=@box.vinyard.address%></p>
          </div>
        </div>
        <div class="flex-column gap2">
          <div class="flex gap1">
            <%= f.label "Make this box available for exchange ?"%>
            <%=f.check_box :exchangeable %>
          </div>
          <div class="flex gap1">
            <div class="flex gap1">
              <%=f.label "delivery method:"%>
              <div>
                <%= f.select :delivery_method,
                options_for_select(["pickup", "shipment"], @box.delivery_method), {}, data: { action: "change->preferences#ToggleAddress", target: "preferences.deliveryMethod"}%>
              </div>
            </div>
            <div class="">
              <div id="address-select" data-preferences-target="address" class="flex gap1">
                <%=f.label "delivery address:"%>
                <div>
                  <%=f.select :address_id, options_for_select(@user.addresses.map {|address| [address.title, address.id]}, @box.address_id) %>
                </div>
              </div>
              <div id="pick-up-date-select" data-preferences-target ="date" class="flex gap1">
                <%= f.label "pick-up date:"%>
                <div id="pick-up-date" data-preferences-target ="pickupdate" class="flex gap1">
                  <%= fields_for :pick_up_date, @box.pick_up_date do |f| %>
                  <span>
                    <%= f.select :date, options_for_select(@slots.map {|slot| [slot.strftime("%d %B %Y")]}, @box.pick_up_date&.date&.strftime("%d %B %Y")), {prompt: "select pick-up date"} %>
                  </span>
                  <%end%>
                </div>

              </div>
            </div>
          </div>
          <div class="flex gap1">
            <%= f.submit "Save"%>
            <button class="closemodal" type="button" data-action="click->preferences#close">close</button>
          </div>
        </div>
      </div>
    <%end%>
  </div>
</div>

app/views/users/_form.html.erb
 <div class="width40 bggrey">
  <div class="padding">
          <h4>exchange</h4>
          <%= form_with model: @exchange, url:user_exchanges_path(@user) do |form|%>
            <%= form.hidden_field :recipient_id, value: @user.id %>
            <%= form.hidden_field :initiator_id, value: current_user.id%>
            <div class="flex-column gap2">
              <%current_year = Time.current.year%>
              <h2> Choose from <%=@user.pseudo%>'s cellar</h2>
              <%= form.fields_for :box_exchanges do |box_exchange|%>
                <div id="select-hidden-recipient">
                  <%= box_exchange.hidden_field :role, value: "recipient"%>
                  <%=box_exchange.select :box_id,
                    @user.boxes.where(exchangeable: true).joins(:dividende)
                 .where(dividende: { year: current_year }).map { |box| ["#{box.dividende.vinyard.name} - #{box.dividende.year}", box.id]},{prompt: "Choose a box"}, {class:"select-recipient"}%>
                </div>
              <%end%>
              <div>
                <%= button_tag "Add boxes", formaction:new_user_box_exchange_path(@user), formmethod: :get, data: { turbo_stream: true }, name: "role", value: "recipient" %>
              </div>
            </div>
            <div class="flex-column gap2">
              <h2> Choose from your cellar</h2>
              <%= form.fields_for :box_exchanges do |box_exchange| %>
                <div id="select-hidden-initiator">
                  <%= box_exchange.hidden_field :role, value: "initiator"%>
                  <%=box_exchange.select :box_id,
                      current_user.boxes.where(exchangeable: true).joins(:dividende)
                 .where(dividende: { year: current_year }).map { |box| ["#{box.dividende.vinyard.name} - #{box.dividende.year}", box.id]},{prompt: "Choose a box"}, {class:"select-initiator"} %>
                </div>

              <%end%>
              <div><%= button_tag "Add boxes", formaction:new_user_box_exchange_path(@user), formmethod: :get, data: { turbo_stream: true }, name: "role", value: "initiator" %>
              </div>
              <div class="">
                <%= form.submit "exchange"%>
              </div>
              <% if flash[:error] %>
                <div class="red">
                  <%= flash[:error] %>
                </div>
              <% end %>
            </div>
          <%end%>
  </div>
</div>

app/views/users/_initiator_box_fields.html.erb
<div data-controller="box-exchange">
  <%= fields_for "exchange[box_exchanges_attributes][#{index}]", BoxExchange.new do |form| %>
    <%= form.hidden_field :role, value: "initiator"%>
    <%= form.select :box_id, boxes.map { |box| ["#{box.dividende.vinyard.name} - #{box.dividende.year}", box.id]},{prompt: "Choose a box"}, {class:"select-initiator"}  %>
  <%end%>
  <button type="button" data-action="click->box-exchange#remove">remove</button>
</div>

app/views/users/_invite.html.erb
<div class="width40 bggrey">
  <div class="padding flex align-center">
  <p> <%=link_to "sign up", new_user_registration_path, id:"text-decoration2" %> or <%=link_to "log in", new_user_session_path, id:"text-decoration2" %> to start exchange boxes !</p>
  </div>
</div>

app/views/users/_recipient_box_fields.html.erb
<div data-controller="box-exchange">
  <%= fields_for "exchange[box_exchanges_attributes][#{index}]", BoxExchange.new do |form| %>
    <%= form.hidden_field :role, value: "recipient"%>
    <%= form.select :box_id, boxes.map { |box| ["#{box.dividende.vinyard.name} - #{box.dividende.year}", box.id]},{prompt: "Choose a box"}, {class:"select-initiator"}  %>
  <%end%>
  <button type="button" class="delete" data-action="click->box-exchange#remove">x</button>
</div>

app/views/users/show.html.erb
<%= render "shared/header"%>
<div class="container">
  <div class="flex-column">
    <div class="margin-bottom-none padding-bottom1">
      <%if current_user%>
        <% if current_user.id != @user.id%>
        <div class="flex space-between">
          <h3 class="margin0"><%=@user.pseudo%>'s cellar</h3>
          <%= link_to user_path(current_user), class:"fit-content align-flex-end" do%>
            <h2 class="hover">my cellar</h2>
          <%end%>
          </div>
        <%else%>
          <div class="flex space-between">
            <%= link_to user_path(@user), class:"height-fit-content" do  %>
            <h3 class="margin0 hover">My cellar</h3>
            <%end%>
            <div class="width40 flex space-between">
              <%= link_to user_exchanges_path(@user), class:"fit-content align-flex-end" do%>
              <h3 class="hover">My exchanges</h2>
            <%end%>
              <h3 class="hover">My documents</h3>
            </div>
          </div>
        <%end%>
      <%else%>
        <h2><%=@user.pseudo%>'s cellar</h2>
      <%end%>
    </div>

    <div class="border-top display flex">
        <div class="width60 relative">
            <div class="margin-bottom2 margin-top2"><h3>Available for exchange</h3></div>
              <div class="grid-box border-bottom margin-bottom2 margin-top2 padding-bottom1">
                <%@exchangeable_boxes.each do |vinyard, boxes|%>
                    <%boxes.each do |box|%>
                      <div class="">

                          <div class="box">
                            <div class="height100 flex-column gap05">

                              <div class=" align-center flex-column">
                                <%=link_to vinyard_path(vinyard) do%>
                                  <h4 class="margin-top-bottom05"><%= vinyard.name %> <%=box.dividende.year%></h3>
                                <%end%>
                                <div class="flex width100 gap05">
                                  <div class="border-bottom width100 height50"></div>
                                  <div class="flex">
                                    <%box.dividende.value.times do%>
                                      <div class="star"></div>
                                    <%end%>
                                  </div>
                                  <div class="border-bottom width100 height50"></div>
                              </div>
                              </div>
                              <div class=" flex ">
                                <% cuvee_colors = box.dividende.dividende_cuvee_colors %>
                                <div class="flex-column gap1">
                                    <% cuvee_colors.each do |cc| %>
                                      <h5 class="">
                                        <%=cc.bottle_quantity%> x <%=cc.cuvee_color.cuvee.name%> <%= "&nbsp;&middot; #{cc.cuvee_color.cuvee.vinyard_appellation.appellation.name}".html_safe %>
                                      </h5>
                                    <%end%>
                                </div>
                              </div>
                            </div>
                          </div>
                          <%if @user == current_user%>
                            <%= link_to "edit preferences", edit_user_box_path(@user, box), data: {turbo_stream: true}, id:"preferences" %>
                          <%end%>

                      </div>
                    <%end%>
                <% end %>
              </div>

            <div class="margin-top2"><h3>other boxes</h3></div>
              <div class="grid-box margin-bottom2 margin-top2 padding-bottom1">
                <%@non_exchangeable_boxes.each do |vinyard, boxes|%>
                  <%boxes.each do |box|%>
                    <div class="">
                        <div class="box">
                          <div class="height100 flex-column gap05">
                           <div class="align-center flex-column">
                              <%=link_to vinyard_path(vinyard) do%>
                                <h4 class="margin-top-bottom05"><%= vinyard.name %> <%=box.dividende.year%></h4>
                              <%end%>
                              <div class="flex width100 gap05">
                                <div class="border-bottom width100 height50"></div>
                                <div class="flex">
                                  <%box.dividende.value.times do%>
                                    <div class="star"></div>
                                  <%end%>
                                </div>
                                <div class="border-bottom width100 height50"></div>
                              </div>
                            </div>
                            <div class=" flex ">
                              <% cuvee_colors = box.dividende.dividende_cuvee_colors %>
                              <div class="flex-column gap1">
                                  <% cuvee_colors.each do |cc| %>
                                    <h5 class="margin1">
                                      <%=cc.bottle_quantity%> x <%=cc.cuvee_color.cuvee.name%> <%= "&nbsp;&middot; #{cc.cuvee_color.cuvee.vinyard_appellation.appellation.name}".html_safe %>
                                    </h5>
                                  <%end%>
                              </div>
                            </div>
                          </div>
                        </div>

                      <%if @user == current_user%>
                        <%= link_to "edit preferences", edit_user_box_path(@user, box), data: {turbo_stream: true}, id:"preferences" %>
                      <%end%>
                    </div>
                  <%end%>
                <%end %>
              </div>
              <div id="modal" class="flex-column">
              </div>
              <div class="border-top">
                <h3 class="margin-top1">Schedule <%=Date.current.year%></h3>
                <div class="grid-address margin-top2">
                  <%@current_boxes.each do |box|%>
                    <%if box.delivery_method == "shipping"%>
                      <%date = box.dividende.shipping_date%>
                    <%else%>
                      <%date = box.pick_up_date&.date&.strftime("%d %b %Y")%>
                    <%end%>
                    <p><%=box.dividende.vinyard.name%></p>
                    <p><%=box.delivery_method%></p>
                    <p><%=date%></p>
                  <%end%>
                </div>

              </div>

        </div>
            <% if current_user && @user.id != current_user.id%>
              <%= render "users/form"%>
              <%elsif current_user && @user.id = current_user.id%>
                <%= render "users/delivery_form"%>
              <%else%>
              <%= render "users/invite"%>
            <%end%>

    </div>
  </div>
</div>