config/routes.rb
Rails.application.routes.draw do
  # get 'box_echanges/new'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  root "vinyards#index"
  # Defines the root path route ("/")
  # root "posts#index"

  #

  resources :appellations

  resources :cuvee_colors

  resources :vinyards do
    member do
      get "shipments_csv", to: "vinyards#shipments_to_csv"
      get "pick_ups_csv", to: "vinyards#pick_ups_to_csv"
      get "edit_description", to: "vinyards#edit_description"
      get "edit_region", to: "vinyards#edit_region"
      get "edit_address", to: "vinyards#edit_address"
    end
    resources :dividendes
    resources :dividende_cuvee_colors
    resources :slots
    resources :vinyard_appellations do
      resources :cuvees
      resources :cuvee_colors
    end
  end

  resources :users, only: [:show] do
    resources :exchanges, only: [:index, :create]
    member do
      post "accept", to: "exchanges#accepted_exchanges"
      post "reject", to: "exchanges#rejected_exchanges"
    end
    resources :box_exchanges, only: [:new, :destroy]
    resources :deliveries, only: [:update]
    resources :addresses, only: [:new, :create, :edit, :update, :destroy]
    resources :boxes, only: [:edit, :update] do
      resources :pick_up_dates, only: [:new, :create, :edit, :update]
    end
  end

    get 'exchanges/load_boxes', to: 'exchanges#load_boxes'

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/dividende.rb
class Dividende < ApplicationRecord
  belongs_to :vinyard
  has_many :boxes, dependent: :destroy
  has_many :users, through: :boxes
  has_many :dividende_cuvee_colors, dependent: :destroy
  has_many :cuvee_colors, through: :dividende_cuvee_colors
  has_many :cuvees, through: :cuvee_colors
  has_many :vinyard_appellations, through: :cuvees
  has_many :slots, dependent: :destroy

  validates :year, presence: true
  validates :shipping_date, presence: true
  validates :value , presence: true , inclusion: { in: (0..3) }

  after_create :create_boxes

  scope :current_year, -> { where(year: Time.current.year) }

  accepts_nested_attributes_for :dividende_cuvee_colors, allow_destroy: true
  accepts_nested_attributes_for :slots, allow_destroy: true

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "id", "id_value", "shipping_date","year", "updated_at", "vinyard_id"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["boxes", "cuvee_colors", "cuvees", "dividende_cuvee_colors", "users", "vinyard", "vinyard_appellations"]
  end

  def create_boxes
    self.vinyard.stock_owners.each do |stock_owner|
      puts "stock_owner.quantity: #{stock_owner.quantity}"
      stock_owner.quantity.times do
        puts "stock_owner.user: #{stock_owner.user}"

        box = Box.create(user: stock_owner.user, stock_owner: stock_owner, vinyard: self.vinyard, dividende: self)


        if box.persisted?
          puts "Box created: #{box.inspect}"
        else
          puts " Box not created: #{box.errors.full_messages}"
        end
      end
    end
  end


end

app/controllers/dividendes_controller.rb
class DividendesController < ApplicationController

  def index
    @dividendes = Dividende.current_year
  end

  def show

  end

  def new
    @vinyard = Vinyard.find(params[:vinyard_id])
    @cuvee_colors = @vinyard.cuvee_colors
    @dividende = Dividende.new
    @dividende.dividende_cuvee_colors.build
    render 'dividendes/new_dividende'
  end

  def create
    @vinyard = Vinyard.find(params[:vinyard_id])
    @cuvee_colors = @vinyard.cuvee_colors
    @dividende = Dividende.new(dividende_params)
    @dividende.vinyard = @vinyard
    if @dividende.save
      redirect_to vinyard_path(@vinyard)
    else
      puts @dividende.errors.full_messages
      render 'dividendes/new_dividende'
    end
  end

  def edit
    @dividende = Dividende.find(params[:id])
    @vinyard = @dividende.vinyard
    @cuvee_colors = @vinyard.cuvee_colors
    render 'dividendes/edit'
  end

  def update
    @dividende = Dividende.find(params[:id])
    @vinyard = @dividende.vinyard
    @cuvee_colors = @vinyard.cuvee_colors
    @dividende.update(dividende_params)
    if @dividende.save
      redirect_to vinyard_path(@vinyard)
    else
      render 'dividendes/edit'
    end
  end

  def destroy
    @dividende = Dividende.find(params[:id])
    @vinyard = @dividende.vinyard
    @dividende.destroy
    redirect_to vinyard_path(@vinyard)
  end




private

  def dividende_params
    params.require(:dividende).permit(:vinyard_id, :year, :shipping_date, :value, dividende_cuvee_colors_attributes: [:cuvee_color_id, :bottle_quantity, :id, :_destroy], slots_attributes:[:id, :start_date, :end_date, :_destroy])
  end
end

app/helpers/dividendes_helper.rb
module DividendesHelper
end

app/views/dividendes/_index_dividendes.html.erb
<%if current_user && current_user == @vinyard.admin%>
            <h3>Dividendes</h3>
            <div class="grid">
              <%@vinyard_dividendes.each do |d|%>
                  <div class="flex-column gap1">
                    <div class="box flex-column gap1">
                      <div class="flex-column">
                        <h4 class="margin-top-bottom05 align-center"><%=d.year%></h4>
                        <div class="flex width100 gap05">
                          <div class="border-bottom width100 height50"></div>
                          <div class="flex">
                            <%d.value.times do%>
                              <div class="star"></div>
                            <%end%>
                          </div>
                          <div class="border-bottom width100 height50"></div>
                        </div>
                      </div>
                      <div class="flex-column gap1">
                        <%d.dividende_cuvee_colors.each do |dcc|%>
                          <div class="flex gap1">
                            <h5><%="#{dcc.bottle_quantity}x #{dcc.cuvee_color.cuvee.name}(#{dcc.cuvee_color.color.color})"%></h5>
                          </div>
                        <%end%>
                      </div>
                    </div>
                    <%=button_to "delete", vinyard_dividende_path(@vinyard, d), method: :delete%>
                  </div>
              <%end%>
            </div>
          <%end%>

app/views/dividendes/_show_dividende.html.erb
  <div class="flex-column width50">
        <div class="flex-column">
          <div class="flex gap1">
            <div class="flex gap1 margin-bottom2">
              <h3 class="margin0">Box <%=@dividende.year%></h3>
              <div class="flex">
                <%@dividende.value.times do%>
                  <div class="star"></div>
                <%end%>
              </div>
            </div>
          </div>
        </div>
        <div class="flex-column gap1">
          <div class="border">
            <%if @bottles.present?%>
              <%@bottles.each_with_index do |bottle,index|%>
                <div class="bottle padding">
                  <div class="flex gap1 border-bottom align-center">
                    <p><%=bottle.bottle_quantity%>x <%=bottle.cuvee_color.cuvee.name%> <%=bottle.cuvee_color.cuvee.vinyard_appellation.appellation.name%></p>
                    <p>- <%=bottle.cuvee_color.color.color%></p>
                  </div>
                  <p><%=simple_format(bottle.cuvee_color.description)%></p>
                </div>
                <%if index != @bottles.size-1%>
                  <div class="border-top"></div>
                <% end %>
              <%end%>
            <%else%>
              <p class="italic">No bottles registered yet</p>
            <%end%>
          </div>
          <div class="flex-wrap">
            <p class="italic margin0"> shipping starts on : <%=@dividende.shipping_date.strftime("%d %B %Y")%></p>
          </div>
          <div class="flex-wrap">
            <p class="italic margin0">pick up available slots :
              <%=@slots.map {|slot| "from #{slot.start_date.strftime("%d %b %Y")} to #{slot.end_date.strftime("%d %b %Y")}"}.join(", ")%>
            </p>
          </div>
          <% if current_user && current_user == @vinyard.admin%>
            <span class="flex space-between">
              <%= link_to "edit dividende", edit_vinyard_dividende_path(@vinyard, @dividende), data: {turbo_stream: true}, class:"button"%>
              <%=link_to "create new dividende", new_vinyard_dividende_path(@vinyard), data: {turbo_stream: true}, class:"button"%>
            </span>
            <div class="" id="dividende">
            </div>

          <%end%>
          <%= render "dividendes/index_dividendes"%>
        </div>
    </div>

app/views/dividendes/edit.turbo_stream.erb
<%=turbo_stream.update "dividende" do %>
  <div class="disable-outside-clik" data-controller="dividende">
    <div class="modale-show">
      <span class="flex flex-end">
        <button type="button" data-action="click->dividende#close">close</button>
      </span>
      <div class="justify-center">
        <%= form_with model:@dividende, url: vinyard_dividende_path(@vinyard, @dividende), method: :patch do |f| %>
          <div class="fields">
            <div class="field">
              <%= f.label :year %>
              <%= f.select :year, options_for_select((Date.today.year..(Date.today.year + 10)).to_a, @dividende.year) %>
            </div>
            <div class="field">
              <%= f.label :shipping_date %>
              <%= f.date_field :shipping_date %>
            </div>
            <div class="field flex-column gap1">
              <%= f.label "pick-up time slots" %>
              <%= f.fields_for :slots do |s| %>
                <div class="flex-column gap1">
                  <div class="flex-column gap1">
                    <%= s.label "from" %>
                    <%= s.date_field :start_date %>
                  </div>
                  <div class="flex-column gap1">
                    <%= s.label "to" %>
                    <%= s.date_field :end_date %>
                  </div>
                </div>
              <%end%>
              <div id="slots"></div>
              <%= button_tag "define new time slots for pick-ups", formaction: new_vinyard_slot_path(@vinyard), formmethod: :get, data: { turbo_stream: true } %>
            </div>
            <div class="field">
              <%= f.label :value %>
              <%= f.select :value, [1,2,3] %>
            </div>
            <div id="dividende-cuvee-colors">
              <%= f.fields_for :dividende_cuvee_colors do |dcc| %>
                <div class="cuvee-color" data-target="dividende.cuveeColor">
                  <div class="field">
                    <%= dcc.label "choose bottle" %>
                    <%= dcc.select :cuvee_color_id, @cuvee_colors.map {|cc| ["#{cc.cuvee.name}, #{cc.cuvee.vinyard_appellation.appellation.name}(#{cc.color.color})", cc.id]} %>
                  </div>
                  <div class="field">
                    <%= dcc.label "choose quantity" %>
                    <%= dcc.number_field :bottle_quantity %>
                  </div>
                  <div class="field">
                    <%= dcc.check_box :_destroy%>
                    <%= dcc.label :_destroy, "delete"%>
                  </div>
                </div>
              <%end%>
            </div>
            <div id="new-bottle"></div>
            <span class="flex flex-end">
              <%= button_tag "add bottles", formaction: new_vinyard_dividende_cuvee_color_path(@vinyard), formmethod: :get, data: { turbo_stream: true } %>
            </span>
          </div>
          <%= f.submit "update" %>
        <%end%>
      </div>
    </div>
  </div>
<%end%>

app/views/dividendes/new_dividende.turbo_stream.erb
<%= turbo_stream.update "dividende" do %>
  <div class="disable-outside-clik" data-controller="dividende">
    <div class="modale-show jutify-center">
      <%= form_with model: @dividende, url: vinyard_dividendes_path(@vinyard), method: :post do |f|%>
        <div class="fields flex-column">
          <div class="field">
            <%= f.label :year %>
            <%= f.select :year, options_for_select((Date.today.year..(Date.today.year + 10)).to_a) %>
          </div>
          <div class="field">
            <%= f.label :shipping_date%>
            <%= f.date_field :shipping_date%>
          </div>
          <div class="field">
            <div id="slots"></div>
            <%= button_tag "define time slots for pick-ups", formaction: new_vinyard_slot_path(@vinyard), formmethod: :get, data:{turbo_stream: true} %>
          </div>
          <div class="field">
            <%=f.label :value%>
            <%=f.select :value, [1,2,3]%>
          </div>

          </div>
            <div id="dividende-cuvee-colors">
              <%=f.fields_for :dividende_cuvee_colors do |dcc|%>
                <div class="field">
                  <%=dcc.label :bottle%>
                  <%=dcc.select :cuvee_color_id, @cuvee_colors.map {|cc| ["#{cc.cuvee.name}, #{cc.cuvee.vinyard_appellation.appellation.name}(#{cc.color.color})", cc.id]}%>
                </div>
                <div class="field">

                  <%= dcc.number_field :bottle_quantity, placeholder:"how many bottle ?"%>
                </div>
              <%end%>
            </div>
            <div id="new-bottle"></div>
            <span class="flex flex-end">
              <%=button_tag "add bottles", formaction:new_vinyard_dividende_cuvee_color_path(@vinyard), formmethod: :get, data:{turbo_stream: true}%>
            </span>
            <p>Creating this dividende will create the boxes for each stock owners.</p>
            <%=f.submit "Create"%>
      <%end%>
      <span class="flex flex-end">
        <button type="button" data-action="click->dividende#close">close</button>
      </span>
      </div>
    </div>
<%end%>